name: Build and deploy Orders API

on:
  push:
    branches:
      - main
    paths:
      - "Orders.Api/**"
      - ".github/workflows/main_orders-api-morteza01.yml"

  workflow_dispatch:

concurrency:
  group: orders-api-production
  cancel-in-progress: true

jobs:
  build:
    name: Build Orders API
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore Orders API
        run: dotnet restore ./Orders.Api/Orders.Api.csproj

      - name: Build Orders API
        run: >
          dotnet build
          ./Orders.Api/Orders.Api.csproj
          --configuration Release
          --no-restore

      - name: Publish Orders API
        run: >
          dotnet publish
          ./Orders.Api/Orders.Api.csproj
          --configuration Release
          --output ./publish
          --no-build

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: orders-api-app
          path: ./publish
          if-no-files-found: error

  deploy:
    name: Deploy Orders API
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: orders-api-app
          path: ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9DC6658A885141D68FD364980F302742 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_715D3A41B0114D4D95F57EB54532E958 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D50235F09A4D4958A81F423B51302996 }}

      - name: Deploy Orders API to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: orders-api-morteza01
          slot-name: Production
          package: ./artifact